services:
  - type: web
    name: law-bot
    env: python
buildCommand: pip install -r main/requirements.txt
startCommand: python main/main.py
    envVars:
      - key: BOT_TOKEN
        value: "..."
      - key: GIGACHAT_TOKEN
        value: "..."
      - key: EMAIL_LOGIN
        value: "..."
      - key: EMAIL_PASSWORD
        value: "..."
      - key: ADMIN_IDS
        value: "..."
