services:
  - type: web
    name: law-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "7947746152:AAGtLCKdA9FjXTio6d6in2Q2YDkcwt2Px5E"
      - key: GIGACHAT_TOKEN
        value: "YWZhZTZlYWUtZjQ2NC00OWYzLTg2N2QtZGQ5ODYyYjM4NGVlOmJlM2FkNzFkLWY1ZDEtNDlkZS1hNmU0LTQ3NTBlOWJiMzRiNg=="
      - key: EMAIL_LOGIN
        value: "kuralbaev777@mail.ru"
      - key: EMAIL_PASSWORD
        value: "@&$os125"
      - key: ADMIN_IDS
        value: "123456789"
