services:
  - type: web
    name: lawyer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
      - key: GIGACHAT_TOKEN
        fromDotEnv: true
      - key: EMAIL_LOGIN
        fromDotEnv: true
      - key: EMAIL_PASSWORD
        fromDotEnv: true
      - key: ADMIN_IDS
        fromDotEnv: true
      - key: OPENAI_API_KEY
        fromDotEnv: true
